services:
  harbour:
    build:
      context: .
    volumes:
      # Mapeie AQUI o SEU fork local (ajuste o caminho conforme sua máquina)
      - ../harbour-core:/src/harbour-core:rw
      # Saída de artefatos
      - ./output:/output
      - ./scripts:/scripts
    working_dir: /src/harbour-core
    command: ["/scripts/build-harbour.sh"]
    restart: "no"
